name: Cookie Refresh

on:
  schedule:
    - cron: '*/30 * * * *'  # Каждый час
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  refresh-cookies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Клонирует репозиторий

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Run the script
      run: python script.py  # Замените на путь к вашему скрипту
      env:
        COOKIES_IN_FILE: "input_files/cookies.json"
        COOKIES_OUT_FILE: "output_files/cookies_out.json"
